using System.Threading.Tasks;
using ArcHive.Model.Search;
using ArcHive.ViewModel;
using ArcHive.ViewModel.Navigation;
using ArcHive.ViewModel.Pages;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Navigation;

namespace ArcHive.View.Pages;

/// <summary>
///     A page view for rendering the list of returned books generated by the
///     OpenLibrary Query API.
/// </summary>
public sealed partial class ListPage : Page
{
    /// <summary>
    ///     A constructor that initializes the view and its viewmodel.
    /// </summary>
    public ListPage()
    {
        InitializeComponent();

        Model = App.Current.Provider.Get<ListPageViewModel>();
    }

    /// <summary>
    ///     The viewmodel of the view.
    /// </summary>
    public readonly ListPageViewModel Model;

    private IPageNavigator? _pageNavigator;
    private BookCardViewModel? _navigationItem;

    private void BookCardView_Clicked(BookCardViewModel obj, string name)
    {
        _navigationItem = obj;
        _pageNavigator?.GoToDetails(_navigationItem.Work);
    }

    protected override void OnNavigatedTo(NavigationEventArgs e)
    {
        base.OnNavigatedTo(e);
        if (e.Parameter is not IPageLoad load) return;

        _pageNavigator = load;
        load.SearchInitiated += InitOnSearchInitiated;

        return;
        Task InitOnSearchInitiated(ISearchFields arg)
        {
            return Model.DoSearch(arg, load);
        }
    }

    private void ResultsCollection_OnLoaded(object sender, RoutedEventArgs e)
    {
        if (_navigationItem is null) return;
        ResultsCollection.ScrollIntoView(_navigationItem);
        ResultsCollection.UpdateLayout();
        ResultsCollection.Focus(FocusState.Programmatic);
    }
}
